USE [913]

UPDATE Bedryf SET bedrnm = 'Test SMT'

update Bedryf set bedrnr= '913'
update AbsenceEntitlements set CompanyCode= '913'
update Absences set Division= '913'
update BacoDiscussions set Company= '913'
update Balance set CompanyCode= '913'
update BankAccounts set Bedrnr= '913'
update BankTransactions set Bedrnr= '913'
update btwtrs set CompanyCode= '913'
update cicmpy set administration= '913'
update cicntp set administration= '913'
update ciFreeFields set Bedrnr= '913'
update ContractParameters set Company= '913'
update DivisionCreditors set Division= '913'
update DivisionDebtors set Division= '913'
update EBLogEntries set Bedrnr= '913'
update facard set Bedrnr= '913'
update gbkmut set CompanyCode= '913'
update grtbk set CompanyCode= '913'
update hrcomp_trans set CompanyCode= '913'
update HRCompanyPeriods set CompanyCode= '913'
update humres set comp= '913'
update ItemCountries set OwnerCompany= '913'
update ItemNumbers set OwnerCompany= '913'
update ItemProcess set Company= '913'
update kstdr set Bedrnr= '913'
update kstpl set Bedrnr= '913'
update laycrd set Bedrnr= '913'
update laydeb set Bedrnr= '913'
update NLSalSettings set Bedrnr= '913'
update Numbers set Companycode= '913'
update PRFreeFields set Division= '913'
update PRProject set Division= '913'
update PublicHolidays set Division= '913'
update recipe set CompanyCode= '913'
update WebStyle set Bedrnr= '913'
update WorkSchedules set CompanyCode= '913'
update BankAccounts set bedrnr='913'
update cicntp set administration='913'
update EBDataQueueEntries set bedrnr='913'
update EBLogEntries set bedrnr='913'
update facard set bedrnr='913'
update humres set comp='913'
update ItemNumbers set OwnerCompany='913'
update kstdr set bedrnr='913'
update kstpl set bedrnr='913'
update laycrd set bedrnr='913'
update laydeb set bedrnr='913'
update PublicHolidays set Division='913'
update dagbk set Division='913'










update Bedryf set bedrnr= '613' where bedrnr='555'
update AbsenceEntitlements set CompanyCode= '613' where CompanyCode='555'
update Absences set Division= '613' where Division='555'
update BacoDiscussions set Company= '613' where Company='555'
update Balance set CompanyCode= '613' where CompanyCode='555'
update BankAccounts set Bedrnr= '613' where Bedrnr='555'
update BankTransactions set Bedrnr= '613' where Bedrnr='555'
update btwtrs set CompanyCode= '613' where CompanyCode='555'
update cicmpy set administration= '613' where administration='555'
update cicntp set administration= '613' where administration='555'
update ciFreeFields set Bedrnr= '613' where Bedrnr='555'
update ContractParameters set Company= '613' where Company='555'
update DivisionCreditors set Division= '613' where Division='555'
update DivisionDebtors set Division= '613' where Division='555'
update EBLogEntries set Bedrnr= '613' where Bedrnr='555'
update facard set Bedrnr= '613' where Bedrnr='555'
update gbkmut set CompanyCode= '613' where CompanyCode='555'
update grtbk set CompanyCode= '613' where CompanyCode='555'
update hrcomp_trans set CompanyCode= '613' where CompanyCode='555'
update HRCompanyPeriods set CompanyCode= '613' where CompanyCode='555'
update humres set comp= '613' where comp='555'
update ItemCountries set OwnerCompany= '613' where OwnerCompany='555'
update ItemNumbers set OwnerCompany= '613' where OwnerCompany='555'
update ItemProcess set Company= '613' where Company='555'
update kstdr set Bedrnr= '613' where Bedrnr='555'
update kstpl set Bedrnr= '613' where Bedrnr='555'
update laycrd set Bedrnr= '613' where Bedrnr='555'
update laydeb set Bedrnr= '613' where Bedrnr='555'
update NLSalSettings set Bedrnr= '613' where Bedrnr='555'
update Numbers set Companycode= '613' where Companycode='555'
update PRFreeFields set Division= '613' where Division='555'
update PRProject set Division= '613' where Division='555'
update PublicHolidays set Division= '613' where Division='555'
update recipe set CompanyCode= '613' where CompanyCode='555'
update WebStyle set Bedrnr= '613' where Bedrnr='555'
update WorkSchedules set CompanyCode= '613' where CompanyCode='555'
update BankAccounts set bedrnr='613' where bedrnr ='555'
update cicntp set administration='613' where administration ='555'
update EBDataQueueEntries set bedrnr='613' where bedrnr ='555'
update EBLogEntries set bedrnr='613' where bedrnr ='555'
update facard set bedrnr='613' where bedrnr ='555'
update humres set comp='613' where comp ='555'
update ItemNumbers set OwnerCompany='613' where OwnerCompany ='555'
update kstdr set bedrnr='613' where bedrnr ='555'
update kstpl set bedrnr='613' where bedrnr ='555'
update laycrd set bedrnr='613' where bedrnr ='555'
update laydeb set bedrnr='613' where bedrnr ='555'
update PublicHolidays set Division='613' where Division ='555'
update dagbk set Division='613' where Division ='555'
