USE [921]

UPDATE Bedryf SET bedrnm = 'Test SAZ'

update Bedryf set bedrnr= '921'
update AbsenceEntitlements set CompanyCode= '921'
update Absences set Division= '921'
update BacoDiscussions set Company= '921'
update Balance set CompanyCode= '921'
update BankAccounts set Bedrnr= '921'
update BankTransactions set Bedrnr= '921'
update btwtrs set CompanyCode= '921'
update cicmpy set administration= '921'
update cicntp set administration= '921'
update ciFreeFields set Bedrnr= '921'
update ContractParameters set Company= '921'
update DivisionCreditors set Division= '921'
update DivisionDebtors set Division= '921'
update EBLogEntries set Bedrnr= '921'
update facard set Bedrnr= '921'
update gbkmut set CompanyCode= '921'
update grtbk set CompanyCode= '921'
update hrcomp_trans set CompanyCode= '921'
update HRCompanyPeriods set CompanyCode= '921'
update humres set comp= '921'
update ItemCountries set OwnerCompany= '921'
update ItemNumbers set OwnerCompany= '921'
update ItemProcess set Company= '921'
update kstdr set Bedrnr= '921'
update kstpl set Bedrnr= '921'
update laycrd set Bedrnr= '921'
update laydeb set Bedrnr= '921'
update NLSalSettings set Bedrnr= '921'
update Numbers set Companycode= '921'
update PRFreeFields set Division= '921'
update PRProject set Division= '921'
update PublicHolidays set Division= '921'
update recipe set CompanyCode= '921'
update WebStyle set Bedrnr= '921'
update WorkSchedules set CompanyCode= '921'
update BankAccounts set bedrnr='921'
update cicntp set administration='921'
update EBDataQueueEntries set bedrnr='921'
update EBLogEntries set bedrnr='921'
update facard set bedrnr='921'
update humres set comp='921'
update ItemNumbers set OwnerCompany='921'
update kstdr set bedrnr='921'
update kstpl set bedrnr='921'
update laycrd set bedrnr='921'
update laydeb set bedrnr='921'
update PublicHolidays set Division='921'
update dagbk set Division='921'










update Bedryf set bedrnr= '613' where bedrnr='555'
update AbsenceEntitlements set CompanyCode= '613' where CompanyCode='555'
update Absences set Division= '613' where Division='555'
update BacoDiscussions set Company= '613' where Company='555'
update Balance set CompanyCode= '613' where CompanyCode='555'
update BankAccounts set Bedrnr= '613' where Bedrnr='555'
update BankTransactions set Bedrnr= '613' where Bedrnr='555'
update btwtrs set CompanyCode= '613' where CompanyCode='555'
update cicmpy set administration= '613' where administration='555'
update cicntp set administration= '613' where administration='555'
update ciFreeFields set Bedrnr= '613' where Bedrnr='555'
update ContractParameters set Company= '613' where Company='555'
update DivisionCreditors set Division= '613' where Division='555'
update DivisionDebtors set Division= '613' where Division='555'
update EBLogEntries set Bedrnr= '613' where Bedrnr='555'
update facard set Bedrnr= '613' where Bedrnr='555'
update gbkmut set CompanyCode= '613' where CompanyCode='555'
update grtbk set CompanyCode= '613' where CompanyCode='555'
update hrcomp_trans set CompanyCode= '613' where CompanyCode='555'
update HRCompanyPeriods set CompanyCode= '613' where CompanyCode='555'
update humres set comp= '613' where comp='555'
update ItemCountries set OwnerCompany= '613' where OwnerCompany='555'
update ItemNumbers set OwnerCompany= '613' where OwnerCompany='555'
update ItemProcess set Company= '613' where Company='555'
update kstdr set Bedrnr= '613' where Bedrnr='555'
update kstpl set Bedrnr= '613' where Bedrnr='555'
update laycrd set Bedrnr= '613' where Bedrnr='555'
update laydeb set Bedrnr= '613' where Bedrnr='555'
update NLSalSettings set Bedrnr= '613' where Bedrnr='555'
update Numbers set Companycode= '613' where Companycode='555'
update PRFreeFields set Division= '613' where Division='555'
update PRProject set Division= '613' where Division='555'
update PublicHolidays set Division= '613' where Division='555'
update recipe set CompanyCode= '613' where CompanyCode='555'
update WebStyle set Bedrnr= '613' where Bedrnr='555'
update WorkSchedules set CompanyCode= '613' where CompanyCode='555'
update BankAccounts set bedrnr='613' where bedrnr ='555'
update cicntp set administration='613' where administration ='555'
update EBDataQueueEntries set bedrnr='613' where bedrnr ='555'
update EBLogEntries set bedrnr='613' where bedrnr ='555'
update facard set bedrnr='613' where bedrnr ='555'
update humres set comp='613' where comp ='555'
update ItemNumbers set OwnerCompany='613' where OwnerCompany ='555'
update kstdr set bedrnr='613' where bedrnr ='555'
update kstpl set bedrnr='613' where bedrnr ='555'
update laycrd set bedrnr='613' where bedrnr ='555'
update laydeb set bedrnr='613' where bedrnr ='555'
update PublicHolidays set Division='613' where Division ='555'
update dagbk set Division='613' where Division ='555'
