USE [961]

UPDATE Bedryf SET bedrnm = 'Test eOrder Kole Transport'

update Bedryf set bedrnr= '961'
update AbsenceEntitlements set CompanyCode= '961'
update Absences set Division= '961'
update BacoDiscussions set Company= '961'
update Balance set CompanyCode= '961'
update BankAccounts set Bedrnr= '961'
update BankTransactions set Bedrnr= '961'
update btwtrs set CompanyCode= '961'
update cicmpy set administration= '961'
update cicntp set administration= '961'
update ciFreeFields set Bedrnr= '961'
update ContractParameters set Company= '961'
update DivisionCreditors set Division= '961'
update DivisionDebtors set Division= '961'
update EBLogEntries set Bedrnr= '961'
update facard set Bedrnr= '961'
update gbkmut set CompanyCode= '961'
update grtbk set CompanyCode= '961'
update hrcomp_trans set CompanyCode= '961'
update HRCompanyPeriods set CompanyCode= '961'
update humres set comp= '961'
update ItemCountries set OwnerCompany= '961'
update ItemNumbers set OwnerCompany= '961'
update ItemProcess set Company= '961'
update kstdr set Bedrnr= '961'
update kstpl set Bedrnr= '961'
update laycrd set Bedrnr= '961'
update laydeb set Bedrnr= '961'
update NLSalSettings set Bedrnr= '961'
update Numbers set Companycode= '961'
update PRFreeFields set Division= '961'
update PRProject set Division= '961'
update PublicHolidays set Division= '961'
update recipe set CompanyCode= '961'
update WebStyle set Bedrnr= '961'
update WorkSchedules set CompanyCode= '961'
update BankAccounts set bedrnr='961'
update cicntp set administration='961'
update EBDataQueueEntries set bedrnr='961'
update EBLogEntries set bedrnr='961'
update facard set bedrnr='961'
update humres set comp='961'
update ItemNumbers set OwnerCompany='961'
update kstdr set bedrnr='961'
update kstpl set bedrnr='961'
update laycrd set bedrnr='961'
update laydeb set bedrnr='961'
update PublicHolidays set Division='961'
update dagbk set Division='961'










update Bedryf set bedrnr= '613' where bedrnr='555'
update AbsenceEntitlements set CompanyCode= '613' where CompanyCode='555'
update Absences set Division= '613' where Division='555'
update BacoDiscussions set Company= '613' where Company='555'
update Balance set CompanyCode= '613' where CompanyCode='555'
update BankAccounts set Bedrnr= '613' where Bedrnr='555'
update BankTransactions set Bedrnr= '613' where Bedrnr='555'
update btwtrs set CompanyCode= '613' where CompanyCode='555'
update cicmpy set administration= '613' where administration='555'
update cicntp set administration= '613' where administration='555'
update ciFreeFields set Bedrnr= '613' where Bedrnr='555'
update ContractParameters set Company= '613' where Company='555'
update DivisionCreditors set Division= '613' where Division='555'
update DivisionDebtors set Division= '613' where Division='555'
update EBLogEntries set Bedrnr= '613' where Bedrnr='555'
update facard set Bedrnr= '613' where Bedrnr='555'
update gbkmut set CompanyCode= '613' where CompanyCode='555'
update grtbk set CompanyCode= '613' where CompanyCode='555'
update hrcomp_trans set CompanyCode= '613' where CompanyCode='555'
update HRCompanyPeriods set CompanyCode= '613' where CompanyCode='555'
update humres set comp= '613' where comp='555'
update ItemCountries set OwnerCompany= '613' where OwnerCompany='555'
update ItemNumbers set OwnerCompany= '613' where OwnerCompany='555'
update ItemProcess set Company= '613' where Company='555'
update kstdr set Bedrnr= '613' where Bedrnr='555'
update kstpl set Bedrnr= '613' where Bedrnr='555'
update laycrd set Bedrnr= '613' where Bedrnr='555'
update laydeb set Bedrnr= '613' where Bedrnr='555'
update NLSalSettings set Bedrnr= '613' where Bedrnr='555'
update Numbers set Companycode= '613' where Companycode='555'
update PRFreeFields set Division= '613' where Division='555'
update PRProject set Division= '613' where Division='555'
update PublicHolidays set Division= '613' where Division='555'
update recipe set CompanyCode= '613' where CompanyCode='555'
update WebStyle set Bedrnr= '613' where Bedrnr='555'
update WorkSchedules set CompanyCode= '613' where CompanyCode='555'
update BankAccounts set bedrnr='613' where bedrnr ='555'
update cicntp set administration='613' where administration ='555'
update EBDataQueueEntries set bedrnr='613' where bedrnr ='555'
update EBLogEntries set bedrnr='613' where bedrnr ='555'
update facard set bedrnr='613' where bedrnr ='555'
update humres set comp='613' where comp ='555'
update ItemNumbers set OwnerCompany='613' where OwnerCompany ='555'
update kstdr set bedrnr='613' where bedrnr ='555'
update kstpl set bedrnr='613' where bedrnr ='555'
update laycrd set bedrnr='613' where bedrnr ='555'
update laydeb set bedrnr='613' where bedrnr ='555'
update PublicHolidays set Division='613' where Division ='555'
update dagbk set Division='613' where Division ='555'
